### ISSUE TITLE
RVV Poly1305 Error

### ISSUE THREAD

**Issue by OMaghiarIMG** [camel-cdr/rvv-bench#2]
Hello, really interesting benchmarks here!
I encountered an error when running the poly1305 vector benchmark:
![image](https://github.com/camel-cdr/rvv-bench/assets/118359779/a970c6a3-3265-402e-be99-1b9598d4ba62)
I'm using GCC 13.1 and QEMU v8.0.

Edit: just noticed the rvv-chacha-poly submodule points to an older commit, changing to latest works.

**Comment by OMaghiarIMG** [comment]
Also noticed the Lichee Pi4A pages links to utf16/32 results which don't exist.
https://camel-cdr.github.io/rvv-bench-results/sipeed_lichee_pi_4a/index.html

Would you be willing to share the code used to generate the charts? curious how the QEMU results look like.

**Comment by camel-cdr** [comment]
> Would you be willing to share the code used to generate the charts?

It's all done in JavaScript, you can just copy one of the directories from the [rvv-bench-results](https://camel-cdr.github.io/rvv-bench-results) repo and replace the embedded json in the html files with the benchmark output. The same goes for the instruction cycles counts, but I've yet to port that to rvv 1.0.
