### ISSUE TITLE
Adding more instructions like scalar?

### ISSUE THREAD

**Issue by furuame** [camel-cdr/rvv-bench#9]
Hello @camel-cdr,

I recently came to use your benchmarks for RVV performance. It's very easy-to-use, really appreciate your work :)

I'd also like to add some tests for scalar instructions to evaluate their performance. Just wondering would I contribute them back upstream? Since this repository is called `rvv-bench`, dunno if you like to keep it specific to RVV.

Also I'd like to add a different but simple pattern like to make strong dependency.
```
add t0, t0, t0
```

Let me know your thoughts! Thanks.

Zen

**Comment by camel-cdr** [comment]
Hi @furuame,
glad to hear that it worked well for you.

I think adding more scalar measurements is great. You need to know how scalar performs in comparison to the vector instructions to effectively make use of them.

> add t0, t0, t0

Is that different from the masked instructions? They have a destination register dependency.

I suppose it's fine to add, although it might require rethinking how the data is presented on the website.

Thanks

**Comment by furuame** [comment]
> > add t0, t0, t0
> 
> Is that different from the masked instructions? They have a destination register dependency.

Yes, for Mask Undisturbed mode in vector extension with vector mask supplied, that's kinda measured the same thing. 

For other scalar or vector instructions, enforcing the register dependency can expose the pipeline latency. It doesn't have to be `{inst} t0, t0, t0`, just needs the destination to be used as a source of the next instruction.

**Comment by camel-cdr** [comment]
Looks great, I'll merge it soon, and then slightly adjust the formatting to my preferences.

I think the `multiline` macro isn't used anywhere, so I'll also remove that. I think I wrote it to benchmark multiple instructions with the existing macros.
